[workspace]
members = [
  "crates/day-01",
  "crates/day-02",
  "crates/day-03",
]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]

[workspace.lints.clippy]
cargo = "warn"
